#!/bin/sh

# Open files.
#
# Usage:
#
# kcr fzf files [paths]

# – fzf (https://github.com/junegunn/fzf)
# – fd (https://github.com/sharkdp/fd)
# – bat (https://github.com/sharkdp/bat)

fd --type file . "$@" |
fzf --preview 'bat --style=numbers --color=always --line-range :500 {}' --prompt='(f)>' |

# Open files
while read file; do
  kcr edit "$file"
done
