#!/bin/sh

# Open buffers.
#
# Usage:
#
# kcr fzf buffers [patterns]

# – fzf (https://github.com/junegunn/fzf)
# – bat (https://github.com/sharkdp/bat)

kcr get --raw %val{buflist} |
grep -F "$*" |
fzf --preview 'kcr cat --raw {} | bat --style=numbers --color=always --line-range :500' --header='Select a buffer to open' --prompt='(b)>' |

# Open buffers
while read name; do
  kcr send buffer "$name"
done
