#!/bin/sh

# Open files by content.
#
# Usage:
#
# kcr fzf grep [paths]

# – fzf (https://github.com/junegunn/fzf)
# – ripgrep (https://github.com/BurntSushi/ripgrep)

rg --column --with-filename '.+' "$@" |
fzf --header='Select a file to open' --prompt='(g)>' |
kcr edit-search
