#!/bin/sh

# Open files by content.
#
# Usage:
#
# kcr fzf grep [paths]

# – fzf (https://github.com/junegunn/fzf)
# – ripgrep (https://github.com/BurntSushi/ripgrep)

fzf --phony --delimiter ':' --ansi --bind 'change:reload(rg --color=always --column --with-filename --fixed-strings -- {q} || true),enter:execute(kcr edit {1} +{2}:{3})+abort' --preview 'highlight_line={2} line_range_begin=$((line = highlight_line - (FZF_PREVIEW_LINES / 4) && line < 1 ? 1 : line)) line_range_end=$((line_range_begin + FZF_PREVIEW_LINES)) && bat --style=numbers --color=always --line-range "$line_range_begin:$line_range_end" --highlight-line {2} {1} 2> /dev/null' --header='Select a file to open' --prompt='(g)>' --query "$*"
