#!/bin/sh

# Open files by content.
#
# Usage:
#
# kcr fzf grep [paths]

# – fzf (https://github.com/junegunn/fzf)
# – ripgrep (https://github.com/BurntSushi/ripgrep)

# Not pretty but robust.
# https://github.com/junegunn/fzf/issues/2581
export PATHS_PATH=$(mktemp)
trap 'rm "$PATHS_PATH"' EXIT
for path do
  echo "$path" >> "$PATHS_PATH"
done

SHELL=sh fzf --phony --delimiter ':' --ansi --bind 'change:reload(while read path; do set -- "$@" "$path"; done < "$PATHS_PATH"; rg --color=always --column --with-filename --fixed-strings -- {q} "$@" || true),enter:execute(kcr edit {1} +{2}:{3})+abort' --preview 'highlight_line={2} line_range_begin=$((line = highlight_line - (FZF_PREVIEW_LINES / 4) && line < 1 ? 1 : line)) line_range_end=$((line_range_begin + FZF_PREVIEW_LINES)) && bat --style=numbers --color=always --line-range "$line_range_begin:$line_range_end" --highlight-line {2} {1} 2> /dev/null' --header='Select a file to open' --prompt='(g)>'
